### ISSUE TITLE
[endorsement] endorser was able to create multiple duplicate endorsements for same candidate

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#117]
Looks like a bug:

https://theboardlist.com/candidate/xiaodi-zhang

![screen shot 2016-05-23 at 10 08 38 am](https://cloud.githubusercontent.com/assets/16053877/15478268/562ce674-20ce-11e6-9b6e-141ac293581c.png)

Can we delete the duplicate endorsements/nominations?

Also, I think the behavior should be that if an endorser submits and endorsement for someone s/he's already endorsed, we should replace the previous endorsement with the new one, but not create a new endorsement.

**Comment by jimmybyrum** [comment]
@lesleykg1 I'm having trouble pinning down how this happened. There is already logic in place to update an endorsement instead of adding a new one, and in my testing it seems to be working ok. Maybe this could be related to merging users? Was Xiaodi or the person who wrote this merged at all?

I've removed the duplicate endorsements from the site.
