### ISSUE TITLE
[admin] changes to user email address not saved

### ISSUE THREAD

**Issue by lesleykg1** [theBoardlist/website#33]
steps to reproduce:
1. as admin, go into Heather Rosato's heatherwrosato@aol.com profile and click EDIT
2. remove the extra period from her email address and click SAVE
3. return to /admin and click into Heather's @aol.com profile, then click EDIT again

expected result:
email appears as "heatherwrosato@aol.com" 

actual result:
email appears as "heatherwrosato@aol..com"

**Comment by lesleykg1** [comment]
I also noticed when you create a new user and then try to find that user in /admin, it isn't there. Maybe changes are not making it back to db?

**Comment by jimmybyrum** [comment]
Both of these should be fixed. The first issue was actually a symptom of another bug. The reason it wasn't saving was because the required fields in the top portion weren't filled out. When you submit now you should see this.
![image](https://cloud.githubusercontent.com/assets/440405/12213915/415af0e4-b637-11e5-9de0-3300223a68c6.png)

On that note, which fields should be required?

**Comment by lesleykg1** [comment]
Should be required:
first name
last name
title
company
email

Location can be optional.
